sudo: required
services:
  - docker
language: generic 
before_install:
  - docker build -t raju6713/docker-learn-react -f Dockerfile.dev .

script:
  - docker run -e CI=true raju6713/docker-learn-react npm run test 
